/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['config.js']) {
  _$jscoverage['config.js'] = [];
  _$jscoverage['config.js'][1] = 0;
}
_$jscoverage['config.js'][1]++;
module.exports = {facebook: {appId: "193097990710217", appSecret: "1242bb60970bff12916baca437cb0492", scope: "email, user_about_me, user_birthday, user_location, publish_stream, friends_location", callback: "http://localhost:3000/auth/facebook"}};
_$jscoverage['config.js'].source = ["module.exports = {","  facebook: {","    appId:      '193097990710217',","    appSecret:  '1242bb60970bff12916baca437cb0492',","    scope:      'email, user_about_me, user_birthday, user_location, publish_stream, friends_location',","    callback:   'http://localhost:3000/auth/facebook'","  }","};"];
